import json
import os
import pickle
from pathlib import Path

import numpy as np

from config import EVA_EMOTIONS, FACE_EMOTIONS, Face2FaceConfig


def get_valid_subject_ids(config: Face2FaceConfig):
    """Get all valid subject IDs from the EEG directory."""
    subject_ids = []
    data_dir = Path(config.eeg_dir)

    for file in os.listdir(data_dir):
        if file.startswith("subject_") and file.endswith("_eeg.pkl"):
            try:
                subject_ids.append(int(file.split("_")[1]))
            except ValueError:
                pass

    subject_ids.sort()
    print(f"Found {len(subject_ids)} valid subjects: {subject_ids}")
    return subject_ids


def load_emoji_data(subject_id, config: Face2FaceConfig):
    """Load emoji landmark data for one subject."""
    data_dir = Path(config.emoji_root_template.format(emoji_size=config.emoji_size))
    data_path = data_dir / f"emoji_vis_subject_{subject_id:02d}.pkl"
    print(f"Loading emoji data: {data_path}")

    try:
        with open(data_path, "rb") as f:
            emoji_data = pickle.load(f)

        emoji_train = emoji_data[0]
        emoji_test = emoji_data[2]

        print(
            f"Subject {subject_id} - train shape: {emoji_train.shape}, "
            f"test shape: {emoji_test.shape}"
        )
        return emoji_train, emoji_test

    except Exception as e:
        print(f"Failed to load emoji data (subject {subject_id}, size {config.emoji_size}): {e}")
        return None, None


def load_face_emotion_labels(config: Face2FaceConfig):
    """Load face emotion labels generated by the face classifier."""
    json_path = Path(config.face_emotion_labels)
    print(f"Loading face emotion labels: {json_path}")
    with open(json_path, "r") as f:
        emotion_data = json.load(f)
    return emotion_data


def load_eeg_data(subject_id, config: Face2FaceConfig):
    """Load EEG data and original emotion labels."""
    eeg_path = Path(config.eeg_dir) / f"subject_{subject_id:02d}_eeg.pkl"
    print(f"Loading EEG data: {eeg_path}")

    try:
        with open(eeg_path, "rb") as f:
            eeg_data = pickle.load(f)

        eeg_train = eeg_data[0]
        eeg_train_labels = eeg_data[1]
        eeg_test = eeg_data[2]
        eeg_test_labels = eeg_data[3]

        print(
            f"Subject {subject_id} - EEG train shape: {eeg_train.shape}, "
            f"test shape: {eeg_test.shape}"
        )
        print(
            f"EEG train label shape: {eeg_train_labels.shape}, "
            f"test label shape: {eeg_test_labels.shape}"
        )

        return eeg_train, eeg_train_labels, eeg_test, eeg_test_labels

    except Exception as e:
        print(f"Failed to load EEG data (subject {subject_id}): {e}")
        return None, None, None, None


def get_face_emotion_label(subject_id, split, sample_idx, frame_idx, emotion_data):
    """Get face emotion label by subject, split, sample index, and frame index."""
    key = f"sub{subject_id:02d}_{split}_sample{sample_idx}_frame{frame_idx}"

    if key in emotion_data:
        return emotion_data[key]["emotion_id"]

    return 6


def prepare_eeg_data(eeg_data, eeg_labels, n_frames=25):
    """Split EEG data into frame-level segments with a 1-second sliding window."""
    n_videos, n_channels, n_times = eeg_data.shape

    window_size = n_times // 10
    step_size = n_times // (10 * 5)

    available_frames = (n_times - window_size) // step_size + 1
    if available_frames < n_frames:
        print(f"Warning: requested {n_frames} frames, but only {available_frames} are available.")
        n_frames = available_frames

    eeg_frames = np.zeros((n_videos, n_frames, n_channels, window_size))

    for video_idx in range(n_videos):
        for frame_idx in range(n_frames):
            start_pos = frame_idx * step_size
            end_pos = start_pos + window_size

            if end_pos <= n_times:
                eeg_frames[video_idx, frame_idx] = eeg_data[video_idx, :, start_pos:end_pos]

    if len(eeg_labels.shape) > 1 and eeg_labels.shape[1] > 1:
        eeg_labels_expanded = np.repeat(eeg_labels, n_frames, axis=0)
    else:
        eeg_labels_expanded = np.repeat(eeg_labels.flatten(), n_frames)

    return eeg_frames, eeg_labels_expanded


def prepare_training_data(subject_id, config: Face2FaceConfig):
    """Prepare train/test EEG and face data with EEG labels and face labels."""
    emoji_train, emoji_test = load_emoji_data(subject_id, config)
    eeg_train, eeg_train_labels, eeg_test, eeg_test_labels = load_eeg_data(subject_id, config)
    face_emotion_labels = load_face_emotion_labels(config)

    if emoji_train is None or emoji_test is None or eeg_train is None or eeg_test is None:
        print(f"Data loading failed. Cannot prepare subject {subject_id}.")
        return None

    print("Processing EEG data with a 1-second window and 0.2-second stride...")
    eeg_train_frames, eeg_train_labels_expanded = prepare_eeg_data(
        eeg_train, eeg_train_labels, config.n_frames
    )
    eeg_test_frames, eeg_test_labels_expanded = prepare_eeg_data(
        eeg_test, eeg_test_labels, config.n_frames
    )

    print(f"Processed EEG train frame shape: {eeg_train_frames.shape}")
    print(f"Processed EEG test frame shape: {eeg_test_frames.shape}")

    eeg_train_frames = eeg_train_frames / np.max(np.abs(eeg_train_frames))
    eeg_test_frames = eeg_test_frames / np.max(np.abs(eeg_test_frames))
    emoji_train = emoji_train.astype(np.float32) / 255.0
    emoji_test = emoji_test.astype(np.float32) / 255.0

    face_train_emotion_labels = []
    face_test_emotion_labels = []

    for vid_idx in range(emoji_train.shape[0]):
        for frame_idx in range(config.n_frames):
            label = get_face_emotion_label(
                subject_id, "train", vid_idx, frame_idx, face_emotion_labels
            )
            face_train_emotion_labels.append(label)

    for vid_idx in range(emoji_test.shape[0]):
        for frame_idx in range(config.n_frames):
            label = get_face_emotion_label(
                subject_id, "test", vid_idx, frame_idx, face_emotion_labels
            )
            face_test_emotion_labels.append(label)

    n_train, frames, channels, window_size = eeg_train_frames.shape
    eeg_train_flat = eeg_train_frames.reshape(-1, channels * window_size)

    n_test, frames, channels, window_size = eeg_test_frames.shape
    eeg_test_flat = eeg_test_frames.reshape(-1, channels * window_size)

    emoji_train_flat = emoji_train.reshape(-1, config.emoji_size, config.emoji_size)
    emoji_train_flat = np.expand_dims(emoji_train_flat, axis=1)

    emoji_test_flat = emoji_test.reshape(-1, config.emoji_size, config.emoji_size)
    emoji_test_flat = np.expand_dims(emoji_test_flat, axis=1)

    print("Data preprocessing finished:")
    print(f"  EEG train data: {eeg_train_flat.shape}")
    print(f"  EEG test data: {eeg_test_flat.shape}")
    print(f"  Emoji train data: {emoji_train_flat.shape}")
    print(f"  Emoji test data: {emoji_test_flat.shape}")
    print(f"  EEG train labels: {len(eeg_train_labels_expanded)}")
    print(f"  EEG test labels: {len(eeg_test_labels_expanded)}")
    print(f"  Face train labels: {len(face_train_emotion_labels)}")
    print(f"  Face test labels: {len(face_test_emotion_labels)}")

    print("\nEEG emotion label distribution:")
    for i, emotion in enumerate(EVA_EMOTIONS):
        count_train = np.sum(eeg_train_labels_expanded == i)
        count_test = np.sum(eeg_test_labels_expanded == i)
        print(f"  {emotion}: train {count_train}, test {count_test}")

    print("\nFace emotion label distribution:")
    for i, emotion in enumerate(FACE_EMOTIONS):
        count_train = face_train_emotion_labels.count(i)
        count_test = face_test_emotion_labels.count(i)
        print(f"  {emotion}: train {count_train}, test {count_test}")

    return {
        "eeg_train": eeg_train_flat,
        "eeg_test": eeg_test_flat,
        "emoji_train": emoji_train_flat,
        "emoji_test": emoji_test_flat,
        "eeg_train_labels": np.array(eeg_train_labels_expanded),
        "eeg_test_labels": np.array(eeg_test_labels_expanded),
        "face_train_labels": np.array(face_train_emotion_labels),
        "face_test_labels": np.array(face_test_emotion_labels),
    }


def collect_all_faces_data(subject_ids, config: Face2FaceConfig):
    """Collect face data from all subjects for face autoencoder pretraining."""
    all_train_faces = []
    all_test_faces = []

    for subject_id in subject_ids:
        print(f"\nCollecting face data for subject {subject_id:02d}...")
        emoji_train, emoji_test = load_emoji_data(subject_id, config)

        if emoji_train is not None and emoji_test is not None:
            emoji_train_flat = emoji_train.reshape(-1, config.emoji_size, config.emoji_size)
            emoji_train_flat = np.expand_dims(emoji_train_flat, axis=1)

            emoji_test_flat = emoji_test.reshape(-1, config.emoji_size, config.emoji_size)
            emoji_test_flat = np.expand_dims(emoji_test_flat, axis=1)

            emoji_train_flat = emoji_train_flat.astype(np.float32) / 255.0
            emoji_test_flat = emoji_test_flat.astype(np.float32) / 255.0

            all_train_faces.append(emoji_train_flat)
            all_test_faces.append(emoji_test_flat)

            print(
                f"  Added {emoji_train_flat.shape[0]} train samples and "
                f"{emoji_test_flat.shape[0]} test samples"
            )

    if all_train_faces and all_test_faces:
        all_train_faces = np.vstack(all_train_faces)
        all_test_faces = np.vstack(all_test_faces)

        print("\nCollection finished.")
        print(f"Total train samples: {all_train_faces.shape[0]}")
        print(f"Total test samples: {all_test_faces.shape[0]}")
        return all_train_faces, all_test_faces

    print("No face data was collected.")
    return None, None

